# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  database_username: <%= ENV['RDS_USERNAME'] %>
  database_password: <%= ENV['RDS_PASSWORD'] %>

development:
  secret_key_base: e2bc38008cbe186549921f71fe35b302e0d11bf934e6759110beeb7d1798d7ff38523134e146e557a3d71a99ce8c2f14cb229f7abe4db49d97e54756d4924b93

test:
  secret_key_base: c3ff2079989864d39500594f9be11d96a843eeef8e2ae4dc5bd309b67ed43305709374c4417ef87e04df1d1bae4fcf540975c455990f58ec58d53c4c4a27c1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
